/**
 * Do not edit this file.
 * To update database, edit <feature>.store.ts
 */
export interface IVersionData {
    cards: number;
    osce_scenarios: number;
    useful_links: number;
    videos: number;
}

export class VersionDataModel implements IVersionData {
    cards: number;
    osce_scenarios: number;
    useful_links: number;
    videos: number;
}
