/**
 * Do not edit this file.
 * To update database, edit <feature>.store.ts
 */
export class Card {
    id: number;
    front: string;
    back: string;
    title: string;
    year: number;
    type: string;
    system: string[];
    CCP: number[];
}