/**
 * Do not edit this file.
 * To update database, edit <feature>.store.ts
 */
export class Scenario {
    id: number;
    year: number;
    system: string;
    title: string;
    question: string;
    script: string;
    expectations: string;
}

export interface IScenario {
    id: number;
    year: number;
    system: string;
    title: string;
    question: string;
    script: string;
    expectations: string;
}