/**
 * Do not edit this file.
 * To update database, edit <feature>.store.ts
 */
export class UsefulLink {
    // id: number; - not needed!
    title: string;
    address: string;
    color: string;
    icon: string;
}